tiiuae/ci-public

vulnix

Simple jenkinsjob to run vulnix SCA tool.
TODO:
- Still has some hardcodings, need to work them out.

Jenkins job to run Vulnix SCA tool.

---

flawfinder

Flawfinder job

---

configs/SpectrumOSBuild.xml
configs/SpectrumOSBuildNUC.xml
configs/flawfinder.xml
configs/vulnix.xml

Initial commit of config.xmls for jenkins jobs.

Configs for the Jenkins jobs

---

configs/TriggerLine.xml
triggerLine

- initial (old) pipeline script
- initial config.xml with inline pipeline script

Initial commit for TriggerLine job

---

hydractl/.gitignore
hydractl/Pipfile
hydractl/hydractl.py

hydractl can add project and a jobset to hydra

Add initial version of hydractl

---

Jenkinsfiles/hydra_copy
Jenkinsfiles/nuc_x86_test_set
Jenkinsfiles/post_processing_nuc
addtimestamp/add_timestamp.py
hydracopy/hydra_copy.sh

Jenkins files from test-automation repo moved to this repo and added addtimestamp.py and hydra_copy.sh (hydrascraper action script)

Jenkinsfiles, addtimestamp and hydracopy added

---

python/validate.py

Initial commit of edDSA signature validation script.

---

Jenkinsfiles/hydra_copy
Jenkinsfiles/post_processing_nuc
addtimestamp/add_timestamp.py
containers/bcache/Dockerfile
containers/bcache/launch.sh
containers/bcache/run.sh
containers/bcache/user.sh
containers/build_bcache.sh
containers/build_hydra.sh
containers/confs/bcache.default
containers/confs/hydra.default
containers/hydra/Dockerfile
containers/hydra/channel.sh
containers/hydra/hydra-configure.sh
containers/hydra/hydra.sh
containers/hydra/launch.sh
containers/hydra/nix_conf.sh
containers/hydra/packages.lst
containers/hydra/populate.sh
containers/hydra/postgres.sh
containers/hydra/run.sh
containers/hydra/upload.sh
containers/hydra/user.sh
containers/run_bcache.sh
containers/run_hydra.sh
hydracopy/hydra_copy.sh
hydractl/hydractl.py
hydrascrape/hydrascrape.py
indexer/indexer.py

Added TII to copyright messages as per new instructions.

Update copyright messages to include TII

---

yubihsm/Dockerfile
yubihsm/build_container.sh
yubihsm/data/.gitignore
yubihsm/debs/.gitignore
yubihsm/debs/get_debs.sh
yubihsm/yubihsm_connector.sh
yubihsm/yubihsm_shell.sh

Preliminary version of the yubihsm docker container setup.

Add yubihsm docker

---

hydrascrape/hydrascrape.py

New hydra post build script is providing a nix store link to build information json file.
This is available to the action script in environment variable HYDRA_POSTBUILD_INFO.
Although all earlier scraped info is still available, action script should extract the build info from the json file in nix store instead in the future.
If downloading of json file fails, action script should just return nonzero value and let the scraper try this again on next round. As the info file just might not have ended up in cache yet.

hydrascrape.py: Scrape post build script info

---

hydrascrape/action.py
hydrascrape/hydrascrape.py
indexer/indexer.py

Enhancements

---

Jenkinsfiles/sbomnix.sh

add sbomnix jenkins job config

Jenkinsfiles: add sbomnix jenkins job config

---

Jenkinsfiles/hydra_copy
Jenkinsfiles/post_processing_nuc

Add sbomnix to post processing pipeline Jenkinsfile
Fixes for using Jenkinsfiles from repository -> removing git clone and pull and change directory paths

Add sbomnix to pipeline

---

containers/hydra/nix_conf.sh

Configured at the container creation time.

hydra: Scale to number of cores

---

indexer/indexer.py
indexer/templates/index_template.html

csvdiff is providing couple of files regarding fixed vulnerabilities and new vulnerabilities, and we want this info to index.html too.
Also changed wildcards for other vulnxscan files, so if there will be e.g. buildtime variants in future, those will be added to the report.

Update indexer to handle vulnerability diffs

---

Jenkinsfiles/hydra_copy
Jenkinsfiles/post_processing_orin

Add Orin post processing Jenkinsfile.
Add vulnsdiff Jenkins job to Jenkins pipeline.

Add Orin post processing Jenkinsfile

---

Jenkinsfiles/hydra_copy

Change Orin post processing triggering before NUC
post processing.

Change order of triggering post processing

---

csvdiff/src/csvdiff.py

Fix an issue introduced in commit a4839dd6 which might cause incorrect diff results due to incorrect inner join in reading back the dropped columns. Also, we need to separately handle non-uid common columns, which is now properly handled with the changes in this commit.

csvdiff: Fix reading back dropped columns

---

containers/hydra/hydra_conf.sh

hydra: Increase max_output_size

---

githooks/check-commit.sh

Also added some positive feedback, if commit message is ok.

Allow long Signed-off-by field in commit message

---

Jenkinsfiles/hydra_copy
Jenkinsfiles/post_processing_nuc
Jenkinsfiles/post_processing_orin

Add Orin USB flashing and boot test to pipeline.

Orin test set pipeline with USB boot

---

Jenkinsfiles/hydra_copy

Update hydra_copy Jenkins file to handle generic-x86_64 jobs as well as nuc jobs.

Update hydra_copy to handle generic-x86_64 builds

---

jenkins/config.xml

Include initial version of jenkins config.xml in it, so git does not prune it as an empty directory.
This is needed to be already able to checkout the directory

jenkins: Create the directory

---

containers/hydra/channel.sh

Do not assume that it's the nix default

hydra: Set channel "22.11" explicitly

---

containers/README.hydra
containers/hydra/Dockerfile
containers/hydra/launch.sh
containers/hydra/messager.py
containers/hydra/postbuild.py

Added usage of messager.py from /home/store

hydra2: Add Slack messaging usage outside Docker image

---

Jenkinsfiles/post_processing_nuc
Jenkinsfiles/post_processing_orin
Jenkinsfiles/provenance.sh
provenance/provenance.py

Initial provenance generation step for the post processing pipeline

Add provenance generation

---

containers/README.hydra
containers/confs/hydra.default
containers/hydra/extracopy.sh
containers/hydra/messager.py
containers/hydra/nix_conf.sh
containers/hydra/run.sh
containers/hydra/upload.sh

- Move conf files under home/confs/
- Rename home/.ssh/key as home/.ssh/bcache.key
- Rename other keys to have .key suffix
- Replace upload_ip.txt and upload_port.txt with shell fragment binarycache.conf
- Replace webserver_ip.txt with shell fragment webserver.conf
- Rename slack_config as slack.config

hydra: Reorganize conf files in store

---

Jenkinsfiles/provenance.sh

This new flag is now available in sbomnix, let's use it.

Add new --depth=1 argument to provenance sbom

---

containers/README.hydra
containers/hydra/example-binarycache.conf
containers/hydra/example-webserver.conf
containers/hydra/extracopy.sh

Configuration should be a bit more consistent and more user friendly.
Should make debugging via log file a bit easier as things are explained with a bit more detail.

extracopy.sh: Better config and error handling

---

containers/hydra/pbhook.sh
containers/hydra/sign.sh

Hydra sign

---

containers/confs/hydra.default

For the benefit of external scripts.

hydra: Add version name to hydra.default

---

containers/build_hydra.sh
containers/confs/hydra.default
containers/run_hydra.sh

Support arbitrary number of entries to container /etc/hosts

hydra: Turn HC_CUSTOM_HOSTS to an array

---

containers/build_hydra.sh
containers/hydra/Dockerfile
containers/hydra/provenance.py
containers/hydra/provenance.sh
provenance/buildtype.md

this PR also adds the buildtype document into the repo.

Provenance ci version info

---

containers/hydra/postbuild.py
containers/hydra/provenance.sh

example runCommand output in hydra UI:
`PROVENANCE_LINK="/nix/store/nrk4pxwkw487p0rix2pdmx8i9vbqpzkd-slsa_provenance_39.json"`

Add provenance files to nix store

---

containers/hydra/postbuild.py
containers/hydra/provenance.py
containers/hydra/provenance.sh

now follows same filename format as buildinfo `{server}-{build_id}-provenance.json`

Change provenance filename to include server name

---

containers/hydra/postbuild.py

This slipped through the code review

Fix provenancesuffix overriding infosuffix

---

Jenkinsfiles/hydra_copy

Change hydra_copy jenkinsfile trigger post processing only Orin agx builds not nx builds.

Change hydra_copy detect only Orin agx builds

---

containers/hydra/postbuild.py

It's always nicer to have prettier code.
Removed "Quitting early" message, as there's an error message anyway if we are quitting early.

Pylintify postbuild.py

---

README.md
docs/bash_script_style_guide.md

Mostly directly converted from Confluence to .md

Add Bash scripting guidelines

---

Jenkinsfiles/hydra_copy

Add posto processing of Orin NX builds, but only
SCS jobs not HW tests yet.

Add Orin NX builds to post processing

---

containers/hydra/provenance.py

HYDRA_JSON doesn't have imageLink, that is only added in postbuild

Fix provenance.py to use format of HYDRA_JSON

---

containers/confs/hydra/example-signing.conf

our signer is not using username "hydra" anymore.

Better default signing.conf

---

Jenkinsfiles/hydra_copy
Jenkinsfiles/post_processing
containers/hydra/compress_outputs.sh
hydrascrape/.gitignore
hydrascrape/action.py
hydrascrape/hydrascrape.py
hydrascrape/unhandle.sh

- Hydrascrape now understands the new values in hydra runcommand log (ganymede)
- buildinfo is taken from provenance
- package, provenance and signatures paths are added to buildinfo
- jenkins pipelines updated to find output path in new location
- improved formatting of jenkins files and removed trailing windows newlines

Use new runcommand format in hydrascrape and update jenkinsfiles accordingly

---

Jenkinsfiles/hydra_copy
Jenkinsfiles/post_processing
Jenkinsfiles/sbomnix.sh
containers/hydra/pbhook.sh
containers/hydra/provenance.sh
hydrascrape/action.py
indexer/.gitignore
indexer/indexer.py

- imageLink is not available anymore, but scs jobs can work with output path
- hw tests still fail when image is not /nixos.img
- post processing can now upload build reports in development mode also
- build reports include hydra-built provenance and compressed output package

Update post processing to work with ganymede

---

Jenkinsfiles/hydra_copy

Add build reports for lenovo X1

---

hydrascrape/action.py

Add image path to buildid.json for jenkins

---

hydrascrape/action.py

the binary cache has a negative cache of 1 hour, run `path-info --refresh` on each path to force up to date info from binary cache.
relevant issue https://github.com/NixOS/nix/issues/4028

Refresh cache narinfo when copying stuff to Jenkins

---

containers/hydra/messager.py

Hydra build info verbal messages revisited (dict way) and pylinted (pep8) as two separate commits.

Verbal build erros pylinted

---

containers/build_hydra.sh
containers/confs/hydra.default
containers/hydra/Dockerfile
containers/hydra/hydra_conf.sh
containers/hydra/packages.lst
containers/hydra/postbuild.py
containers/hydra/run.sh
hydrascrape/action.py
pullrequests/PRBuilder.md
pullrequests/PollPR.py
pullrequests/setenv.sh

Backport baseline updates to ganymede.

Ganymede updt

---

Jenkinsfiles/hydra_copy
Jenkinsfiles/post_processing
Jenkinsfiles/signature-verification.sh

Add signature verification job to Jenkins pipeline for both output and provenance.

Add signature verification to Jenkins pipeline

---

Jenkinsfiles/post_processing

Add stopping post processing pipeline if signature verification fails.

Stop post processing if signature verification fails

---

Jenkinsfiles/signature-verification.sh

Use tmp directory for temporary files on
signature verification job

Use tmp directory on verification job

---

Jenkinsfiles/hydra_copy
Jenkinsfiles/post_processing
Jenkinsfiles/upload_dir_creation.sh

Add build results directory creation to webserver
if there is no directory already.

Build results directory creation

---

pullrequests/PollPR.py

Reduced Github RestApi calls. Catching possbile rate limit errors

Reduce Github rate limit errors

---

Jenkinsfiles/hydra_copy

Enable HW test to lenovoX1 builds to run HW tests on lenovoX1 laptop.

Enable HW tests to lenovoX1 builds

---

Jenkinsfiles/hydra_copy
Jenkinsfiles/post_processing
hydrascrape/.gitignore
hydrascrape/action.py
hydrascrape/hydrascrape.py

Folder is created for each server based on hydra build info `Server` key, and the build json files and handled_builds are saved in there.
Also includes commit for formatting the files with `black` as that is our python standard now.

Handle servers in their own folders

---

containers/README.hydra
containers/hydra/messager.py

Added two channel usage possibility for Slacking build results (good/bad news). Channels can be configured be ON/OFF (to drop of for example ok build news)

Add Slacking possibility to two channels

---

Jenkinsfiles/hydra_copy

Add post processing triggering for fmo project builds.

Add fmo builds to post processing

---

containers/hydra/hydra_conf.sh

hydra: Set output limit to 20000000000 bytes

---

containers/hydra/nix_conf.sh

Please add some kind of description what this change is about.

hydra: Add github:ipetkov to allowed URIs
