- hydrascrape/.gitignore
- hydrascrape/hydrascrape.py
projects and jobsets can now be selected with regular expressions. You could even handle all builds on a hydra server by setting both project regexp and jobset regexp to ".*"
locking file is used to stop hydrascrape running concurrently for same set of projects/jobsets. Parallel runs are still possible by setting different handled builds file for each.
Just make sure that patterns don't match same jobsets, or builds in those jobsets will be handled several times.
Handled builds file needs to be explicitly given as a parameter now.
> Add regexp matching and process locking

- hydractl/hydractl.py
Added all possible options for projects and jobsets, so you can change all options that you can set in hydra gui. While also keeping sane defaults so you don't have to use every option possible.
This can also be more easily expanded to support modifying of existing projects and jobsets and to delete projects and jobsets.
> Make hydractl more flexible

- Jenkinsfiles/hydra_copy
- Jenkinsfiles/post_processing_nuc
- addtimestamp/add_timestamp.py
- hydracopy/hydra_copy.sh
- hydractl/hydractl.py
- hydrascrape/hydrascrape.py
- indexer/indexer.py
Apache-2.0 is the correct license for code files.
Also updated copyright year markings.
> Change SPDX license entries to Apache-2.0

- postbuild/postbuild.py
This postbuild script will add the build information json file and a symbolic link to image to nix/store.
The names of the added items are printed on stdout, so they can be scraped by hydrascraper from run command logs in hydra's web ui.
Link and json file are expected to be copied to cache in a cron job.
> Add Hydra postbuild script

- githooks/check-commit.sh
- install-hooks.sh
Added script for automatic checking of commit messages. A script for installing hooks needs to be run before hook is in use.
Enforces non empty subject line
Enforces subject line length <= 50 characters
Enforces body line lenghts <= 72 characters
Enforces empty line after subject
Enforces single Signed-off-by field
Moves Signed-off-by field to the end of the commit message
Warns about subject capitalization (Not enforcing, user may ignore)
Warns about subject mood (Not enforcing, user may ignore)
Warnings are not enforced, as the checks are not fool proof. It might complain about a correctly formatted subject, in that case user has the option to ignore the warning.
Most of the checking script imported from the old buildroot project, with minimal changes.
> Add githook for checking commit messages

- yubihsm/Dockerfile
- yubihsm/build_container.sh
- yubihsm/yubihsm.sh
- yubihsm/yubihsm_connector.sh
- yubihsm/yubihsm_shell.sh
Unified all yubihsm scripts into single script.
Required debs are fetched automatically when building the container. Yubihsm connector is now started as daemon.
Container is now run as a normal unprivileged user. There are options to define which user is used.
Added udev rule installation (for debian based systems)
> Improve yubihsm container script

- yubihsm/yubihsm.sh
Udev triggering was triggering virtual replug of all repluggable devices on the system earlier. Now only the yubihsm2 devices are triggered after udev rules update.
Also changed 'bash' command so that it will use the default user unless '--uid' or '--user' was defined.
> Trigger only yubihsm2 devices when updating rules

- containers/hydra/Dockerfile
- containers/hydra/hydra_conf.sh
- containers/hydra/run.sh
Make it possible to fetch results size of the
final image from the remote builder.
> hydra: Fix "Output limit exceeded"

- Jenkinsfiles/vulnsdiff.sh
This PR adds a shell script that runs https://github.com/tiiuae/ci-public/tree/main/csvdiff to compare vulnxscan result files from two builds.
> vulnsdiff: Initial commit

- hydrascrape/action.py
There is a time frame when Hydra UI has other build information, but the postbuild script has not been run yet. After this change the processing the build will be retried on the next scraper run.
Earlier, a build without runcommand logs was assumed to be old one from the time before postbuild script, and thus it was just marked as handled one.
By now all the old builds should be already in the handled builds list, and we can assume all builds will have postbuild info eventually.
> action.py: Return nonzero if no postbuild info

- Jenkinsfiles/vulnsdiff.sh
- csvdiff/src/csvdiff.py
- csvdiff/tests/resources/left_cols_dups.csv
- csvdiff/tests/resources/right_cols_dups.csv
- csvdiff/tests/test_csvdiff.py
- vulnsdiff: start using the new '--cols' command-line argument, as well as the '--ignoredups' to make it correctly identify vulnerabilities. Add comment that explains the need for those two command-line arguments.
- csvdiff: change --cols so that it accepts comma-separated string of column names. Earlier space-separated list caused issues in running the script in pytest.
- csvdiff: add a new test case to jointly test the usage of '--cols' and '--ignoredups'.
> vulnsdiff: Start using cols and ignoredups

- csvdiff/src/csvdiff.py
- csvdiff/tests/test_csvdiff.py
- Don't drop columns that were not considered in diffing
- Fix relevant test case
> csvdiff: Don't drop groupby columns

- containers/hydra/nix_conf.sh
- containers/run_hydra.sh
This matches default nix installation outside containers, and is required to make containerized hydra to produce the same hashes as outside world.
> hydra: Enable sandboxing

- containers/confs/hydra.default
- containers/run_hydra.sh
With a new configuration entry HC_CUSTOM_HOSTS, one custom hosts entry can be added for the container.
> hydra: Add support for /etc/hosts entries

- containers/hydra/Dockerfile
- containers/hydra/run.sh
- containers/hydra/schedule.sh
This makes build info generated on the postbuild hook to get uploaded to the cache, when container so configured.
> hydra: Run extracopy.sh every two minutes

- containers/hydra/webcopy.sh
```
Instead of previously hardcoded list of known targets, 
use full target name as destination directory name.
Destination directory is created on web server if it does not exist.
e.g. "<hash>-intel-nuc-debug-nixos.img" file will go to directory 
"<origin>/intel-nuc-debug/<hash>-intel-nuc-debug-nixos.img"
instead of earlier "<origin>/nuc/<hash>-intel-nuc-debug-nixos.img".
```
> webcopy.sh: Use target name as destination dir

- containers/hydra/postbuild.py
Set POSTBUILD_MSGSCRIPT environment variable to run a script after postbuild has done it's stuff.
Useful for e.g. sending build status messages.
> postbuild.py: Run messaging script if configured

- containers/hydra/packages.lst
Update packages.lst to preinstall currently
unbuildable source packages.
> hydra: Support nixos-23.05 based ghaf

- containers/README.hydra
- containers/hydra/Dockerfile
- containers/hydra/messager.py
- containers/hydra/run.sh
Build information send to Slack if configuration done. Activation requires slack_config file to exists in containers/store/home Content need to be 1) Slack secret auth token 2) Used Slack channel
> Add support for Slack messaging

- indexer/indexer.py
The provenance file is already uploaded to the webserver with everything else in the results folder, so adding it to the build report is as simple as making the html template aware of it.
> Add provenance to build report

- containers/run_bcache.sh
- containers/run_hydra.sh
- containers/run_jenkins_agent.sh
- containers/run_jenkins_controller.sh
`#!/bin/bash` does not work on NixOS systems. Use `#!/usr/bin/env bash` for compatibility across all platforms.
> Use #!/usr/bin/env bash shebang

- containers/hydra/extracopy.sh
Now if e.g. host is not in known_hosts you'll get an error, instead of any interactive prompts. (Preferred action in a cron job)
> extracopy.sh: Use batch mode for sftp and scp

- containers/run_hydra.sh
Based on the base label. Makes it possible for future scripts to access the container by a known name.
> run_hydra.sh: Name the container

- containers/README.hydra
- containers/hydra/Dockerfile
- containers/hydra/example-signing.conf
- containers/hydra/nix_conf.sh
- containers/hydra/pbhook.sh
- containers/hydra/sign.sh
Just create a signature file, to see that signing functionality is there. This exact form is unlikely to be used as the final way to transfer the singature.
> hydra: Support package signing

- containers/run_hydra.sh
We never need that, and it breaks autodeployment setups.
> hydra: Don't run container in interactive mode

- .gitignore
- containers/hydra/Dockerfile
- containers/hydra/hydra_conf.sh
- containers/hydra/install-sbomnix.sh
- containers/hydra/postbuild.py
- containers/hydra/provenance.py
- containers/hydra/provenance.sh
- sbomnix gets installed during the container build
- postbuild.py runs provenance.sh, which in turn runs sbomnix and provenance.py
- the resulting provenance file is located in `/home/hydra/results/$BUILD_ID/`
I also reorganized the dockerfile commands so it doesn't have to rebuild the whole container when one (insignificant) file is changed, but instead can use the docker cache effectively.
> Generate provenance in hydra container

- containers/hydra/postbuild.py
this makes it possible to
`nix copy --from https://cache.vedenemo.dev /nix/store/path/to/provenance.json`
after the build is done, as long as the hydra container has the proper binarycache.conf
> Upload provenance file to the binary cache server

- Jenkinsfiles/signature-verification.sh
- Using https://github.com/tiiuae/scs-pki-research/tree/feature/yubikey_signing
- Takes two nix store paths as inputs
- Job fails if signature is not valid
Not added to any pipelines yet
> Add signature verification jenkins job

- sha256tree/sha256tree.py
Should calculate hash for almost anything found on filesystem.
Will produce the same hash as sha256sum for plain files.
My suggestion for calculating a relevant hash for directories.
For any errors encountered there will be full python error output, as errors are not specifically handled, but the main thing is that execution will return nonzero in that case.
> Add directory tree hashing script

- sha256tree/sha256tree.py
Usage help is available.
Debug can be enabled on command line.
Buffer size can be set.
Plain mode for getting just the hash, no need for 'cutting' the output to get just the hash in another script.
> Enhance sha256tree with some options

- containers/hydra/install-sbomnix.sh
Simply updates the sbomnix hash in hydra container to point to latest version. Tested to have no effect on provenance but we might as well use the latest one.
> Update sbomnix to the latest version

- containers/confs/hydra.default
- containers/hydra/provenance.py
- containers/hydra/provenance.sh
- containers/run_hydra.sh
Adds ability to save some env variables from confs, so they can be read from within the container. Builder ID is constructed from HYDRA_URL config value, which is set to publicly available url such as `https://hydra2.vedenemo.dev/` in production. This also makes server name available in internalParameters.
> Generate BuilderId and server name for provenance

- containers/hydra/postbuild.py
- containers/hydra/provenance.py
- containers/hydra/provenance.sh
- containers/hydra/run.sh
Provenance script is now modular and self contained like slack messaging is. 
- Set in run.sh with `POSTBUILD_PROVENANCE_SCRIPT`.
- Can be run on it's own without depending on postbuild.py
- Reads hydra information from env variables.
> Refactor provenance generation to a separate file

- containers/hydra/Dockerfile
Build test behaves as the "latest 2.18.0 based Nix image"
> Docker tagging, using latest stale 2.17.0 as Hydra base image

- containers/hydra/postbuild.py
after some investigation, I have found out `pbhook.sh` is not even being run on the final build output images (at least not all of them). This was an oversight that was never properly tested.
This change makes postbuild upload any outputs and derivations that are missing. Yes, it can still fail, but that will fail the whole RunCommand and it will be a visible failure. 
More reliable periodically scanning uploader with retry functionality might be developed in the future to replace this.
> Upload build outputs separately to cache

- containers/run_hydra.sh
run_hydra.sh was exiting without any explanation when setting up known_hosts failed.
> hydra: Log error after failed ssh-keyscan

- autodeployment/relaunch_hydra.sh
It's not an error if there's no old container to clean away.
> autodeployment: Silence false error message

- containers/hydra/packages.lst
Update list of packages needed for bootstrapping builds on the hydra container to match current ghaf version, and the nixpkgs it uses.
> packages.lst: Update

- Jenkinsfiles/hydra_copy
Enable HW test to risc-v builds to run HW tests
on Polarfire.
> Enable HW tests to risc-v builds

- Jenkinsfiles/hydra_copy
fixes hydra_copy job when the server directory is not created yet.
> hotfix: Handled_builds in nonexistant directory

- README.md
- checksig/checksig.md
- checksig/checksig.sh
Added checksig.sh for end user signature checking of Ghaf build packages and provenance files.
Wrote some instructions for using it.
> Add easy to use signature checking script

- containers/confs/hydra.default
- containers/run_hydra.sh
Adds hydra config option `HC_RESTART_CONTAINER` which when set to "yes" adds `--restart always` to the container flags.
Using restart policy `unless-stopped` was not sufficient as the container exits with error code 255 when the host machine is rebooted, causing it to not actually restart.
> Add config option to restart container on reboot

- containers/hydra/webupload.sh
As long as webserver uses standard ssh port 22 this would've worked, but now it's like it should be and port could be nonstandard.
> Fix missing ssh port in webupload.sh

- containers/hydra/nix_conf.sh
Nix no longer allows "github:" uris by default, so they have to be allowed explicitly
> hydra: Update allowed-uris

- containers/hydra/nix_conf.sh
- git+https://github.com/tiiuae/
- github:nixos/
Access to these repositories is already allowed by other names (different protocol / different capitalization of the name). It was decided that instead of changing the references in the repository, hydra is made to allow also these alternative names.
> hydra: Add allowed uris for FMO-OS

- containers/hydra/provenance.sh
sbomnix 1.5.0 release renamed `--type=buildtime` to `--buildtime`
> Fix sbomnix after update

- containers/hydra/nix_conf.sh
Make hydra container able to build i686 code, for setups where remote builders are not used for that.
> hydra: Add ability to build i686 code

- Jenkinsfiles/hydra_copy
Fix for getting riscv builds in
post processing after naming change.
> Fix for riscv build naming
